name: Build & deploy Hugo site

on:
  push:
    branches:
      - hugo

  # Publish posts whose publishDate has passed even if there are no new pushes.
  schedule:
    - cron: "0 6 * * *" # Daily at 06:00 UTC (08:00 CEST)

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.166.0
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
